site_name: SiteWatch
site_dir: site
docs_dir: docs
site_description: Documentation for SiteWatch
dev_addr: 'localhost:8111'
repo_url: https://github.com/digitalutsc/site_watch/tree/gh-pages
theme: material
nav:
    - Home: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Writing Tests: writing-test-data.md
    - Output: output.md
    - Contributing: contributing.md
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
extra_css:
    - css/extra.css
edit_uri: 'edit/main/docs/'