site_name: SiteWatch
site_dir: site
docs_dir: docs
site_description: Documentation for SiteWatch
dev_addr: 'localhost:8111'
repo_url: https://github.com/digitalutsc/site_watch
theme: material
nav:
    - Home: index.md
markdown_extensions:
  - admonition
extra_css:
    - css/extra.css