site_name: SiteWatch
site_dir: site
docs_dir: docs
site_description: Documentation for SiteWatch
dev_addr: 'localhost:8111'
repo_url: https://github.com/digitalutsc/site_watch/tree/gh-pages
theme: 
    name: material
    features:
      - content.code.copy
      - content.code.select
      - content.code.annotate
      - content.code.annotate
      - meta.author
nav:
    - Home: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Writing Tests: writing-test-data.md
    - Output: output.md
    - Contributing: contributing.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
    - css/extra.css
edit_uri: 'edit/main/docs/'